### PR TITLE
Upgrade to latest docker-ce and to docker-compose 1.15.0 (for compose file version 3 support)

### PR DESCRIPTION
**Pull request by gesterhuizen**
Upgrade to latest docker-ce and to docker-compose 1.15.0 (for compose file version 3 support)

### CODE REVIEW

**Comment by tamarrow-zz** [comment]
Looks fine. Is this version backwards compatible for everyone who is already running on the older versions?

**Comment by gesterhuizen** [comment]
From what I could see, `docker-compose` maintained backwards compatibility as newer versions can read the old version compose files. According to my reading of https://docs.docker.com/compose/compose-file/, all releases maintain backwards compat.

With Docker engine, they do deprecate and break some stuff during upgrades:
* https://docs.docker.com/engine/breaking_changes/
* https://docs.docker.com/engine/deprecated/#driver-specific-log-tags

A quick scan of that list doesn't lead me to believe that it would affect us (as I don't recall us depending on the specific changes). But it's a very fluffy argument, worthy of challenge.

**Comment by gesterhuizen** [comment]
What would be required to get this approved and merged ?

**Comment by gesterhuizen** [comment]
@alberts @achille-roussel  @tamarrow: any suggestions for next steps to getting this merged ? 

Without this, we cannot use a recent version of `docker-compose` (i.e. any one which uses a V2 or later compose file) in any projects which we build using this image (and, hence, https://github.com/segmentio/golang-private-image, which is the current state-of-the-art CI image according to my understanding).

**Comment by tamarrow-zz** [comment]
If we verified this works for this config: https://github.com/segmentio/golang-private-image/blob/master/files/circle.yml than LGTM

**Review by achille-roussel — APPROVED** [review]
@gesterhuizen 

Build golang-image or golang-private-image locally using this base image, if you can do a successful `circle run` then this is good to go 👍 

There's a small chance it'll break someone's build so just make sure you drop a message in #guild-engineering about the change, then if someone sees their build break it would be good to update the README with instructions on how to fix.

Thanks for the PR!

**Comment by achille-roussel** [comment]
@gesterhuizen does this still need to be merged?

**Pull request closed without merging**
